# PyKMIP Configuration File for EDB TDE KMIP Client Tests
# Connects to Cosmian KMS KMIP socket server (TLS + client cert auth)

[client]
host=127.0.0.1
port=15696
certfile=test_data/certificates/client_server/owner/owner.client.acme.com.crt
keyfile=test_data/certificates/client_server/owner/owner.client.acme.com.key
ca_certs=test_data/certificates/client_server/ca/ca.crt
cert_reqs=CERT_NONE
ssl_version=PROTOCOL_SSLv23
do_handshake_on_connect=True
