---
services:
  no-authentication:
    image: ${DOCKER_IMAGE_NAME}
    ports:
      - 9998:9998
  tls-authentication:
    image: ${DOCKER_IMAGE_NAME}
    volumes:
      - ./../../test_data:/data
    command: --tls-p12-file /data/client_server/server/kmserver.acme.com.p12 --tls-p12-password password --authority-cert-file /data/client_server/ca/ca.crt
      --socket-server-start --socket-server-port 5696 --socket-server-hostname 0.0.0.0
    ports:
      - 9999:9999
      - 5696:5696
    environment:
      - KMS_PORT=9999
