---
services:
  no-authentication:
    image: ${DOCKER_IMAGE_NAME}
    ports:
      - 9998:9998
  tls-authentication:
    image: ${DOCKER_IMAGE_NAME}
    volumes:
      - ./../../test_data:/data
    command: >-
      --tls-p12-file /data/certificates/client_server/server/kmserver.acme.com.p12
      --tls-p12-password password
      --authority-cert-file /data/certificates/client_server/ca/ca.crt
      --socket-server-start
      --socket-server-port 5696
      --socket-server-hostname 0.0.0.0
    ports:
      - 9999:9999
      - 5696:5696
    environment:
      - KMS_PORT=9999
  tls13-authentication:
    image: ${DOCKER_IMAGE_NAME}
    volumes:
      - ./../../test_data:/data
    command: >-
      --tls-p12-file /data/certificates/client_server/server/kmserver.acme.com.p12
      --tls-p12-password password
      --tls-cipher-suites "TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256:TLS_AES_128_CCM_SHA256"
      --authority-cert-file /data/certificates/client_server/ca/ca.crt
      --socket-server-start
      --socket-server-port 5697
      --socket-server-hostname 0.0.0.0
    ports:
      - 10000:10000
      - 5697:5697
    environment:
      - KMS_PORT=10000
