---
# tasks file for ansible/roles/tpm

- name: Check OS distribution
  debug:
    var: ansible_distribution

- name: Copy cosmian_fstool script
  ansible.builtin.copy:
    src: /tmp/cosmian_fstool
    dest: /usr/sbin/
    remote_src: true
    owner: root
    group: root
    mode: 0500

- name: TPM packages installation on Ubuntu
  when: ansible_distribution == 'Ubuntu'
  block:
  - name: Update all packages to their latest version
    apt:
      update_cache: yes

  - name: Install packages
    apt:
      name: tpm2-tools
      state: latest
      update_cache: yes

- name: TPM packages installation on RedHat
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'
  block:
  - name: Update all packages to their latest version
    dnf:
      update_cache: yes

  - name: Install packages
    ansible.builtin.dnf:
      name: 
        - tpm2-tools 
        - cryptsetup
      state: present
      update_cache: yes

- name: TPM packages installation on Amazon-linux
  when: ansible_distribution == 'Amazon'
  block:
  - name: Update all packages to their latest version
    dnf:
      update_cache: yes

  - name: download and unzip tpm2-tools
    unarchive:
      src: https://package.cosmian.com/tpm2-tools/tpm2-tools-amazonlinux-20240116.zip
      dest: /tmp/
      remote_src: yes

  - name: install tpm2-tools
    shell: ./install.sh
    args:
      chdir: /tmp/tpm2-tools

  - name: clean tpm2-tools
    file:
      path: /tmp/tpm2-tools/
      state: absent

  - name: Install packages tpm2-tss
    ansible.builtin.dnf:
      name: tpm2-tss
      state: present
      update_cache: yes
