---
services:

  # === Oracle TDE HSM stack ===
  # Start with: docker compose up -d
  # Wipe with docker compose down -v
  oracle:
    container_name: oracle
    #image: container-registry.oracle.com/database/free:23.9.0.0-lite
    image: container-registry.oracle.com/database/free:latest-lite
    ports:
      - 1521:1521
    environment:
      ORACLE_PWD: '1234'
      ENABLE_ARCHIVELOG: 'true'
      ENABLE_FORCE_LOGGING: 'true'
    healthcheck:
      test: [CMD, /opt/oracle/checkDBStatus.sh]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s  # Oracle 23.9 lite prend ~2min à boot la première fois

  kms-oracle:
    container_name: kms-oracle
    image: ghcr.io/cosmian/kms:latest
    ports:
      - 9998:9998
    networks:
      default:
        aliases:
          - kms
    depends_on:
      oracle:
        condition: service_healthy
    environment:
      RUST_LOG: cosmian_kms_server=trace
      COSMIAN_PKCS11_LOGGING_LEVEL: trace
    volumes:
      - ./oracle/cosmian-kms:/cosmian-kms
