---
# tasks file for ansible/roles/configure_ima

- name: Check OS distribution
  debug:
    var: ansible_distribution

- name: Create ima folder
  file:
    path: /etc/ima
    state: directory
    owner: root
    group: root
    mode: "0500"

- name: Copy ima policy
  ansible.builtin.copy:
    src: /tmp/ima-policy
    dest: /etc/ima/
    remote_src: true
    owner: root
    group: root
    mode: "0400"

- name: Copy the bash script to the remote host (in order to update the grub conf)
  copy:
    content: |
      #!/usr/bin/bash
      f=/etc/default/grub

      ## Hash method
      if grep -q ima_hash= $f ; then
        # Hash method already set
        sed -i 's/ima_hash=[^ "]\+/ima_hash=sha256/' $f
      else
        # Hash method not set
        sed -i /GRUB_CMDLINE_LINUX=/s/\"$/\ ima_hash=sha256\"/ $f
      fi

      ## Template format
      if grep -q ima_template= $f ; then
        # Template format already set
        sed -i 's/ima_template=[^ "]\+/ima_template=ima-ng/' $f
      else
        # Template format not set
        sed -i /GRUB_CMDLINE_LINUX=/s/\"$/\ ima_template=ima-ng\"/ $f
      fi
    dest: /tmp/grub.sh
    mode: "0700" # Make the script executable
    remote_src: yes

- name: Update the grub configuration
  command: "/tmp/grub.sh"

- name: Remove the update grub configuration script
  file:
    path: "/tmp/grub.sh"
    state: absent

# Update grub
- name: Update grub on Ubuntu
  when: ansible_distribution == 'Ubuntu'
  block:
    - name: Update grub
      ansible.builtin.command:
        cmd: update-grub

- name: Update grub on RedHat
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky' or ansible_distribution == 'Amazon'
  block:
    - name: Update grub
      ansible.builtin.command:
        cmd: grub2-mkconfig -o /etc/grub2.cfg

    - name: Selinux - allow https
      ansible.builtin.command:
        cmd: setsebool -P httpd_can_network_connect 1
