[package]
name = "cosmian_kms_utils"
version = "4.11.3"
authors = ["Bruno Grieder <bruno.grieder@cosmian.com>"]
edition = "2021"
license-file = "../../LICENSE.md"


[dependencies]
cosmian_kmip = { path = "../kmip", features = ["openssl"] }
openssl = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
