[package]
name = "cosmian_kms_utils"
version = "4.11.3"
authors = ["Bruno Grieder <bruno.grieder@cosmian.com>"]
edition = "2021"
license-file = "../../LICENSE.md"


[dependencies]
# argon2 = "0.5"
cloudproof = { workspace = true }
cosmian_kmip = { path = "../kmip", features = ["openssl"] }
# cosmian_kms_crypto = { path = "../crypto" }
# cosmian_logger = { path = "../logger" }
# num-bigint-dig = { workspace = true }
openssl = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
# tracing = { workspace = true }
# zeroize = { workspace = true }
