[package]
name = "cosmian_kms_utils"
version = "4.8.2"
authors = ["Bruno Grieder <bruno.grieder@cosmian.com>"]
edition = "2021"
license-file = "../../LICENSE.md"

[features]
curve25519 = []

[dependencies]
argon2 = "0.5.0"
cloudproof = { workspace = true }
cosmian_crypto_core = "9.3.0"       # Must use `crypto_core` from `cloudproof_rust` reexport
cosmian_kmip = { path = "../kmip" }
num-bigint = { workspace = true }
openssl = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
