[package]
authors = ["Bruno Grieder <bruno.grieder@cosmian.com>"]
edition = "2021"
name = "cosmian_kms_utils"
version = "0.1.0"

[features]
curve25519 = []

[dependencies]
abe_policy = "1.0"
bitflags = "1.2"
cosmian_crypto_base = "2.1"
cosmian_kmip = { path = "../kmip" }
cosmian_cover_crypt = "7.0"
cosmian_crypto_core = "4.0"
hex = { version = "0.4", features = ["serde"] }
num-bigint = { version = "0.4", features = ["rand", "serde"] }
rand_core = "0.6"
rand_hc = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0.20"
tracing = "0.1"

[target.'cfg(all(not(target_arch = "wasm32"), not(windows)))'.dependencies]
cosmian_crypto_base = { version = "2.1", features = ["libsodium"] }

[dev-dependencies]
tracing-log = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-tree = "0.2"
