[package]
name = "cosmian_kms_utils"
version = "4.5.0"
authors = ["Bruno Grieder <bruno.grieder@cosmian.com>"]
edition = "2021"
license-file = "../../LICENSE.md"

[features]
curve25519 = []

[dependencies]
argon2 = "0.5.0"
cloudproof = { workspace = true }
cosmian_crypto_core = { workspace = true }
cosmian_kmip = { path = "../kmip" }
num-bigint = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tiny-keccak = { version = "2.0.2", features = ["shake"] } # TODO(E.C): should be fixed in cosmian_crypto_core
tracing = { workspace = true }
