[package]
name = "cosmian_kms_utils"
version = "4.4.2"
authors = ["Bruno Grieder <bruno.grieder@cosmian.com>"]
edition = "2021"

[features]
curve25519 = []

[dependencies]
aes = "0.8"
argon2 = "0.5.0"
bitflags = { workspace = true }
cloudproof = { workspace = true }
cosmian_kmip = { path = "../kmip" }
leb128 = { workspace = true }
num-bigint = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tracing-log = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-tree = { workspace = true }
