import { UploadOutlined } from "@ant-design/icons";
import { Button, Card, Form, Input, Select, Space, Upload, Tabs } from "antd";
import React, { useEffect, useRef, useState } from "react";
import { useAuth } from "./AuthContext";
import { sendKmipRequest } from "./utils";
import { import_ttlv_request, parse_import_ttlv_response } from "./wasm/pkg";
import ExternalLink from "./components/ExternalLink";

interface ImportAwsKekFormData {
    kekFile?: Uint8Array;
    kekBase64?: string;
    keyArn?: string;
    wrappingAlgorithm: string;
    keyId?: string;
}

type KeyImportResponse = {
    UniqueIdentifier: string;
};

const WRAPPING_ALGORITHMS = [
    { label: "RSAES_OAEP_SHA_1", value: "rsaes-oaep-sha1" },
    { label: "RSAES_OAEP_SHA_256", value: "rsaes-oaep-sha256" },
    { label: "RSA_AES_KEY_WRAP_SHA_1", value: "rsa-aes-key-wrap-sha1" },
    { label: "RSA_AES_KEY_WRAP_SHA_256", value: "rsa-aes-key-wrap-sha256" },
    { label: "SM2PKE (China region only)", value: "sm2pke" },
];

const ImportAwsKekForm: React.FC = () => {
    const [form] = Form.useForm<ImportAwsKekFormData>();
    const [res, setRes] = useState<undefined | string>(undefined);
    const [isLoading, setIsLoading] = useState(false);
    const { idToken, serverUrl } = useAuth();
    const responseRef = useRef<HTMLDivElement>(null);
    const [inputType, setInputType] = useState<"file" | "base64">("file");

    useEffect(() => {
        if (res && responseRef.current) {
            responseRef.current.scrollIntoView({ behavior: "smooth" });
        }
    }, [res]);

    const onFinish = async (values: ImportAwsKekFormData) => {
        setIsLoading(true);
        setRes(undefined);
        try {
            const tags = ["aws", `wrapping_algorithm:${values.wrappingAlgorithm}`];
            // only include key_arn if provided:
            if (values.keyArn) {
                tags.push(`key_arn:${values.keyArn}`);
            }
            const keyUsage = ["WrapKey", "Encrypt"];

            let kekData: Uint8Array | undefined = undefined;
            let kekFormat: string | undefined = undefined;

            if (inputType === "file" && values.kekFile) {
                kekData = values.kekFile;
                kekFormat = "pkcs8";
            } else if (inputType === "base64" && values.kekBase64) {
                // Decode base64 to Uint8Array
                const binary = atob(values.kekBase64.replace(/\s/g, ""));
                const bytes = new Uint8Array(binary.length);
                for (let i = 0; i < binary.length; i++) {
                    bytes[i] = binary.charCodeAt(i);
                }
                kekData = bytes;
                kekFormat = "pkcs8";
            } else {
                setRes("Please provide the KEK as a file or base64 string.");
                setIsLoading(false);
                return;
            }

            const request = import_ttlv_request(
                values.keyId || null, // Custom key ID
                kekData, // Key bytes
                kekFormat, // Format type
                undefined, // Public key ID
                undefined, // Private key ID
                undefined, // Certificate ID
                false, // Unwrap flag
                true, // Replace existing
                tags, // Tags array
                keyUsage, // Key usage
                undefined // Wrapping key ID
            );

            const result_str = await sendKmipRequest(request, idToken, serverUrl);
            if (result_str) {
                const result: KeyImportResponse = await parse_import_ttlv_response(result_str);
                setRes(`AWS KEK has been successfully imported - Key ID: ${result.UniqueIdentifier}`);
            }
        } catch (e) {
            setRes(`Error importing AWS KEK: ${e}`);
            console.error("Error importing AWS KEK:", e);
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="p-6">
            <h1 className="text-2xl font-bold mb-6">Import AWS Key Encryption Key (KEK)</h1>
            <div className="mb-8 space-y-2">
                <p>Import an RSA Public Key Encryption Key (KEK) generated by AWS KMS.</p>
                <p>
                    The KEK should be provided as a <b>raw binary file</b> (recommended) or as a <b>base64-encoded string</b>.
                </p>
                {/* prettier-ignore */}
                <p className="text-sm text-gray-600">
                    See AWS KMS developer documentation for {" "}
                <ExternalLink href="https://docs.aws.amazon.com/kms/latest/developerguide/importing-keys.html">
                    downloading the wrapping public key and import token
                </ExternalLink>.
                </p>
            </div>
            <Form form={form} onFinish={onFinish} layout="vertical">
                <Space direction="vertical" size="middle" style={{ display: "flex" }}>
                    <Card>
                        {/* prettier-ignore */}
                        <Tabs
                            activeKey={inputType}
                            onChange={(key) => setInputType(key as "file" | "base64")}
                            items={[
                                {
                                    key: "file",
                                    label: "Upload KEK File (raw binary)",
                                    children: (
                                        <Form.Item
                                            name="kekFile"
                                            label="KEK File"
                                            rules={inputType === "file" ? [{ required: true, message: "Please upload the KEK file" }] : []}
                                            help="The KEK file as exported from your HSM or key generator (DER format, .der or .bin file - not PEM)"
                                        >
                                            <Upload
                                                beforeUpload={(file) => {
                                                    const reader = new FileReader();
                                                    reader.onload = (e) => {
                                                        const content = e.target?.result;
                                                        if (content instanceof ArrayBuffer) {
                                                            const bytes = new Uint8Array(content);
                                                            form.setFieldsValue({ kekFile: bytes });
                                                        }
                                                    };
                                                    reader.readAsArrayBuffer(file);
                                                    return false;
                                                }}
                                                maxCount={1}
                                            >
                                                <Button icon={<UploadOutlined />}>Select KEK File</Button>
                                            </Upload>
                                        </Form.Item>
                                    ),
                                },
                                {
                                    key: "base64",
                                    label: "Paste Base64-encoded KEK",
                                    children: (
                                        <Form.Item
                                        name="kekBase64"
                                        label="KEK (base64)"
                                        rules={
                                            inputType === "base64"
                                            ? [{ required: true, message: "Please paste the base64-encoded KEK" }]
                                            : []
                                        }
                                        help={
                                            <>
                                                    Paste the base64-encoded KEK (as exported from{" "}
                                                <ExternalLink href="https://docs.aws.amazon.com/kms/latest/developerguide/importing-keys-get-public-key-and-token.html#importing-keys-get-public-key-and-token-api">
                                                    AWS KMS API
                                                </ExternalLink>)
                                                </>
                                            }
                                        >
                                            <Input.TextArea rows={4} placeholder="Base64-encoded KEK" />
                                        </Form.Item>
                                    ),
                                },
                            ]}
                        />
                    </Card>
                    <Card>
                        <h3 className="text-m font-bold mb-4">Wrapping Algorithm</h3>
                        <Form.Item
                            name="wrappingAlgorithm"
                            label="Wrapping Algorithm"
                            rules={[{ required: true, message: "Please select the wrapping algorithm" }]}
                            help="Select the algorithm used to wrap key material"
                        >
                            <Select options={WRAPPING_ALGORITHMS} />
                        </Form.Item>
                    </Card>
                    <Card>
                        <h3 className="text-m font-bold mb-4">AWS Key ARN</h3>
                        <Form.Item name="keyArn" label="AWS Key ARN" help="The Amazon Resource Name (ARN) of the AWS KMS key (optional)">
                            <Input placeholder="arn:aws:kms:..." />
                        </Form.Item>
                    </Card>
                    <Card>
                        <h3 className="text-m font-bold mb-4">KMS Key ID</h3>
                        <Form.Item
                            name="keyId"
                            label="Key ID in the Cosmian KMS"
                            help="The unique ID for this key in the KMS. A random UUID will be generated if not specified."
                        >
                            <Input placeholder="Custom Key ID (optional)" />
                        </Form.Item>
                    </Card>
                    <Form.Item>
                        <Button type="primary" htmlType="submit" loading={isLoading} className="w-full text-white font-medium">
                            Import AWS KEK
                        </Button>
                    </Form.Item>
                </Space>
            </Form>
            {res && (
                <div ref={responseRef}>
                    <Card title="Import Response">{res}</Card>
                </div>
            )}
        </div>
    );
};

export default ImportAwsKekForm;
