[package]
name = "cosmian_kms_python"
version = "4.2.0"
authors = ["Hugo Rosenkranz-Costa <hugo.rosenkranz@cosmian.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "cosmian_kms"

[dependencies]
abe_policy = { git = "https://github.com/Cosmian/abe_policy", branch = "fix/interfaces" }
cosmian_kmip = { path = "../kmip" }
cosmian_kms_client = { path = "../client" }
cosmian_kms_utils = { path = "../utils" }
leb128 = "0.2"
pyo3 = { version = "0.17.3", features = ["extension-module", "abi3", "abi3-py37", "generate-import-lib"] }
pyo3-asyncio = { version = "0.17.0", features = ["tokio-runtime"] }
serde_json = "1.0"
tokio = { version = "1.24", features = ["full"] }
