{{- if .Values.kms.database.url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cosmian-kms.fullname" . }}-db
  labels:
    {{- include "cosmian-kms.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.kms.database.url | quote }}
{{- end }}
