[package]
name = "kms_test_server"
version = "4.13.3"
edition = "2021"

[lib]
name = "kms_test_server"
crate-type = ["dylib"]

[dependencies]
actix-server = { version = "2.3", default-features = false }
assert_cmd = "2.0.14"
base64 = { workspace = true }
cosmian_kmip = { path = "../kmip" }
cosmian_kms_client = { path = "../client", default-features = false }
cosmian_kms_server = { path = "../server", features = [
    "insecure",
], default-features = false }
etcetera = "0.8.0"
regex = "1.10.3"
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
zeroize = { workspace = true }
