---
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  external_labels:
    cluster: ${KMS_CLUSTER}
    environment: production

scrape_configs:
  - job_name: otel-collector
    static_configs:
      - targets:
          - otel-collector:8888
        labels:
          service: otel-collector-metrics
