// Field names intentionally share a prefix (`jwks_endpoint_*`) for disambiguation
// in flat CLI / env-var namespaces.  The same prefix appears in the structs
// generated by `ConfigArgs`, so we suppress the lint at file level.
#![allow(clippy::struct_field_names)]

use clap::Args;
use clap_config_fallback::ConfigArgs;
use serde::{Deserialize, Serialize};

/// Configuration for the `GET /.well-known/jwks.json` public-key-discovery endpoint.
///
/// This endpoint *publishes* the server's own public keys as a RFC 7517 JSON Web Key Set
/// so that external JWT verifiers can discover the keys.
///
/// It is **distinct** from the `JwksManager` used internally to *fetch* public keys
/// from identity providers in order to validate incoming bearer tokens.
#[derive(Debug, Args, ConfigArgs, Deserialize, Serialize, Clone)]
#[serde(default)]
pub struct JwksEndpointConfig {
    /// Enable the `GET /.well-known/jwks.json` endpoint.
    ///
    /// When set, the server publicly exposes all active public keys whose
    /// `CryptographicUsageMask` includes `Verify` as a RFC 7517 JSON Web Key Set.
    /// The endpoint is **unauthenticated** — no credentials are required to fetch it,
    /// and no authentication middleware is applied. Defaults to `false`.
    #[clap(
        long,
        env = "KMS_JWKS_ENDPOINT_ENABLED",
        default_value_t = false,
        verbatim_doc_comment
    )]
    pub jwks_endpoint_enabled: bool,

    /// Maximum number of public keys returned in a single JWKS response.
    ///
    /// When the server holds more eligible keys than this limit, the response is
    /// truncated and an `X-JWKS-Truncated: true` header is added to signal consumers.
    /// Increase this value if your deployment performs frequent key rotation and all
    /// overlapping verification keys must be simultaneously discoverable.
    #[clap(
        long,
        env = "KMS_JWKS_ENDPOINT_MAX_KEYS",
        default_value_t = 50,
        verbatim_doc_comment
    )]
    pub jwks_endpoint_max_keys: usize,
}

impl Default for JwksEndpointConfig {
    fn default() -> Self {
        Self {
            jwks_endpoint_enabled: false,
            jwks_endpoint_max_keys: 50,
        }
    }
}
