[package]
name = "ckms_pkcs11"
version = "4.13.3"
edition = "2021"

[lib]
name = "ckms_pkcs11"
crate-type = ["dylib"]

[dependencies]
#native-pkcs11 = "0.2.16"
#native-pkcs11-traits = "0.2.16"
cosmian_kmip = { path = "../kmip" }
cosmian_kms_client = { path = "../client" }
etcetera = "0.8.0"
native-pkcs11 = { path = "native-pkcs11/native-pkcs11" }
native-pkcs11-traits = { path = "native-pkcs11/native-pkcs11-traits" }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
zeroize = { workspace = true }