---
apiVersion: v2
name: cosmian-kms
description: A Helm chart for deploying Eviden KMS, a FIPS 140-3 compliant Key Management System, on Kubernetes.
type: application
version: 5.26.0
appVersion: 5.26.0
kubeVersion: '>=1.24.0-0'
home: https://github.com/Cosmian/kms
sources:
  - https://github.com/Cosmian/kms
keywords:
  - kms
  - key-management
  - kmip
  - cryptography
  - fips
  - cosmian
maintainers:
  - name: Cosmian
    url: https://cosmian.com
icon: https://raw.githubusercontent.com/Cosmian/kms/develop/documentation/docs/images/cosmian_logo.png
annotations:
  artifacthub.io/license: BUSL-1.1
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/Cosmian/kms
    - name: Documentation
      url: https://docs.cosmian.com/installation/kubernetes_helm/
  artifacthub.io/images: |
    - name: kms-fips
      image: ghcr.io/cosmian/kms-fips:5.26.0
    - name: kms
      image: ghcr.io/cosmian/kms:5.26.0
