use cosmian_findex_server::config::JwtAuthConfig;

// Test auth0 Config
pub(crate) const AUTH0_JWT_ISSUER_URI: &str = "https://findex-server.eu.auth0.com/";
pub(crate) const AUTH0_TOKEN: &str = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjVPNXRnb25CVWtYdFcyei1TM2VqNiJ9.eyJmaW5kZXhTZXJ2ZXJVc2VyR3JvdXAiOiJjMmY2MzYwM2M4MTdiYmEzMjgxOGJjMTc4N2IyZTgxMzk5YzY1MTIyOWQ2MGUxZmVhZTNjMTg0ZWJlZWIwNTI5Iiwibmlja25hbWUiOiJ0ZWNoIiwibmFtZSI6InRlY2hAY29zbWlhbi5jb20iLCJwaWN0dXJlIjoiaHR0cHM6Ly9zLmdyYXZhdGFyLmNvbS9hdmF0YXIvNTJmYjMxYzhjY2FkMzQ1ODEyM2Q0ZmFkMTQwODU0Y2Y_cz00ODAmcj1wZyZkPWh0dHBzJTNBJTJGJTJGY2RuLmF1dGgwLmNvbSUyRmF2YXRhcnMlMkZ0ZS5wbmciLCJ1cGRhdGVkX2F0IjoiMjAyNC0xMC0yNVQxMToyODowNC4xMzBaIiwiZW1haWwiOiJ0ZWNoQGNvc21pYW4uY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJpc3MiOiJodHRwczovL2ZpbmRleC1zZXJ2ZXIuZXUuYXV0aDAuY29tLyIsImF1ZCI6InRmM0F6OTB0eTJUck5yeEo5M3hpRnBDRkJuVU9sSXhEIiwiaWF0IjoxNzI5ODU1Njg0LCJleHAiOjE3NjEzOTE2ODQsInN1YiI6ImF1dGgwfDY3MWI4MGE4MDMwMGM5NjhhM2UyOTk2ZiIsInNpZCI6IlRrMkpfRDFiRTdQdjhWczhUMWRPbGJjdHBJTnJYQmdVIiwibm9uY2UiOiJXRGd6UW00d1dHcElSaTFIZERVMVRESitMak5OZEZKSmVqUnlTMkZIVTJzeVFuYzJlSEZUY0d0M1J3PT0ifQ.HRlV79HTrxzXp1mGhLgyni6LV4l1wTBieOMoapvr9Yi5BF3tiKKaHaQsPFsxigAiAZ2J1q5AiUooyT-M3NMggwwW5RMhbeyDYnJwp6ucDMOTdT2dXmDvtn0BMzbUx3wmedve_oEjzfO8vRk_RhD9wDxfB1ZAZRytYblJFHxWUdaKTJkH7f3VMkpl9cVjqkw1U3j2FLp9BuZ-q5jkiQLqCFTBvTAJ1jQaZqwcIlXA547sYzkTPg8otv8IS3nief0TTvv-GpvCXxETHoQVWmpO-g8PW9UkeHe3cHZ57A7juVOHgH_9zh8-uzXfZxMZo69gfjs-tVydoDOsmYhWTEgf5w";

pub(crate) fn get_auth0_jwt_config() -> JwtAuthConfig {
    JwtAuthConfig {
        jwt_issuer_uri: Some(vec![AUTH0_JWT_ISSUER_URI.to_owned()]),
        jwks_uri: None,
        jwt_audience: None,
    }
}
