[package]
name = "proteccio_pkcs11_loader"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Proteccio HSM PKCS#11 loader"

[lib]
doctest = false

[dependencies]
async-trait = { workspace = true }
cosmian_kms_interfaces = { path = "../../interfaces" }
hex = { workspace = true }
libloading = "0.8.5"
lru = { workspace = true }
pkcs11_sys = { path = "../sys" }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
rand = "0.9.0-alpha.2"
zeroize = { workspace = true }
uuid = { version = "1.11.0", features = ["v4"] }

[dev-dependencies]
serial_test = { version = "3.1.1", default-features = false }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { workspace = true }


[features]
# Enable this feature to run Proteccio tests (they require a Proteccio HSM)
proteccio = []