[package]
name = "cosmian_logger"
version = "4.14.2"
authors = ["Emmanuel Coste <emmanuel.coste@cosmian.com>"]
edition = "2021"
license-file = "../../LICENSE"

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
