[package]
name = "cosmian_logger"
version = "4.10.1"
authors = ["Emmanuel Coste <emmanuel.coste@cosmian.com>"]
edition = "2021"
license-file = "../../LICENSE.md"

[dependencies]
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
