---
# tasks file for no_updates

- name: Check OS distribution
  debug:
    var: ansible_distribution

- name: Disable automatic updates on Ubuntu
  when: ansible_distribution == 'Ubuntu'
  block:
    - name: Disable auto upgrade services
      systemd:
        name: "{{ item }}"
        enabled: no
        state: stopped
      with_items:
        - unattended-upgrades
        - apt-daily
        - apt-daily-upgrade
        - snapd
        - apt-daily-upgrade.timer
        - apt-daily.timer
        - snapd.socket

    - name: Update APT configuration to disable automatic updates
      lineinfile:
        path: /etc/apt/apt.conf.d/10periodic
        regexp: 'APT::Periodic::Update-Package-Lists "1";'
        line: 'APT::Periodic::Update-Package-Lists "0";'
        backup: yes

    - name: Update APT cache
      ansible.builtin.apt:
        autoclean: yes
        update_cache: yes
  tags: ubuntu

- name: Disable automatic updates on Red Hat
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky' or ansible_distribution == 'Amazon'
  block:
    - name: Populate service facts
      service_facts:

    - name: Disable dnf-automatic service
      systemd:
        name: dnf-automatic.timer
        enabled: no
        state: stopped
      when: "'dnf-automatic' in services"

    - name: Disable automatic updates in dnf.conf
      lineinfile:
        path: /etc/dnf/dnf.conf
        line: "check_update=0"
        backup: yes

    - name: Check if automatic.conf exists
      stat:
        path: /etc/dnf/automatic.conf
      register: __dnf_automatic_conf

    - name: Update automatic.conf to disable automatic updates download
      lineinfile:
        path: /etc/dnf/automatic.conf
        regexp: "download_updates = yes"
        line: "download_updates = no"
        backup: yes
      when: __dnf_automatic_conf.stat.exists

    - name: Update automatic.conf to disable automatic updates apply
      lineinfile:
        path: /etc/dnf/automatic.conf
        regexp: "apply_updates = yes"
        line: "apply_updates = no"
        backup: yes
      when: __dnf_automatic_conf.stat.exists

    - name: Clean Yum metadata
      command: dnf clean all

    - name: Update DNF cache
      dnf:
        update_cache: yes
  tags: redhat
