// This file is @generated by prost-build.
// Source proto: src/provider.proto (v1alpha1)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VersionRequest {
    /// Version of the Secrets Store CSI Driver.
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VersionResponse {
    /// Version of the Secrets Store CSI Driver.
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    /// Name of the Secrets Store CSI Driver Provider.
    #[prost(string, tag = "2")]
    pub runtime_name: ::prost::alloc::string::String,
    /// Version of the Secrets Store CSI Driver Provider. Must be semver-compatible.
    #[prost(string, tag = "3")]
    pub runtime_version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MountRequest {
    /// Attributes is the JSON-serialized parameters field from the SecretProviderClass.
    #[prost(string, tag = "1")]
    pub attributes: ::prost::alloc::string::String,
    /// Secrets is the secret content referenced in nodePublishSecretRef (deprecated).
    #[prost(string, tag = "2")]
    pub secrets: ::prost::alloc::string::String,
    /// TargetPath is the path to which the volume will be published (deprecated).
    #[prost(string, tag = "3")]
    pub target_path: ::prost::alloc::string::String,
    /// Permission is the file permissions (deprecated).
    #[prost(string, tag = "4")]
    pub permission: ::prost::alloc::string::String,
    /// CurrentObjectVersion is the list of currently-mounted object versions.
    #[prost(message, repeated, tag = "5")]
    pub current_object_version: ::prost::alloc::vec::Vec<ObjectVersion>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MountResponse {
    #[prost(message, repeated, tag = "1")]
    pub object_version: ::prost::alloc::vec::Vec<ObjectVersion>,
    #[prost(message, optional, tag = "2")]
    pub error: ::core::option::Option<Error>,
    /// files contains the entire mount volume filesystem.
    #[prost(message, repeated, tag = "3")]
    pub files: ::prost::alloc::vec::Vec<File>,
}
/// File holds secret file contents and location in the mount path.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct File {
    /// The relative path of the file within the mount.
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    /// The mode bits used to set permissions on this file (decimal, 0–511).
    #[prost(int32, tag = "2")]
    pub mode: i32,
    /// The file contents.
    #[prost(bytes = "vec", tag = "3")]
    pub contents: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ObjectVersion {
    /// Id is the unique object identifier in the external secrets store.
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Version is the object version fetched from the external secrets store.
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Error {
    /// Code is the error code returned by the provider, used for metrics.
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod csi_driver_provider_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Secrets Store CSI Driver Provider service.
    #[derive(Debug, Clone)]
    pub struct CsiDriverProviderClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl CsiDriverProviderClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> CsiDriverProviderClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> CsiDriverProviderClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            CsiDriverProviderClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Version returns the runtime name and version of the provider.
        pub async fn version(
            &mut self,
            request: impl tonic::IntoRequest<super::VersionRequest>,
        ) -> std::result::Result<tonic::Response<super::VersionResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/v1alpha1.CSIDriverProvider/Version",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("v1alpha1.CSIDriverProvider", "Version"));
            self.inner.unary(req, path, codec).await
        }
        /// Mount executes the mount operation in the provider.
        pub async fn mount(
            &mut self,
            request: impl tonic::IntoRequest<super::MountRequest>,
        ) -> std::result::Result<tonic::Response<super::MountResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/v1alpha1.CSIDriverProvider/Mount",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("v1alpha1.CSIDriverProvider", "Mount"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod csi_driver_provider_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
        clippy::unwrap_used,
    )]
    use tonic::codegen::*;
    /// Trait that providers must implement.
    #[async_trait]
    pub trait CsiDriverProvider: std::marker::Send + std::marker::Sync + 'static {
        /// Version returns the runtime name and version of the provider.
        async fn version(
            &self,
            request: tonic::Request<super::VersionRequest>,
        ) -> std::result::Result<tonic::Response<super::VersionResponse>, tonic::Status>;
        /// Mount executes the mount operation: fetch secrets from KMS and return
        /// file contents to be written to the pod tmpfs volume.
        async fn mount(
            &self,
            request: tonic::Request<super::MountRequest>,
        ) -> std::result::Result<tonic::Response<super::MountResponse>, tonic::Status>;
    }
    /// Secrets Store CSI Driver Provider service.
    #[derive(Debug)]
    pub struct CsiDriverProviderServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> CsiDriverProviderServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for CsiDriverProviderServer<T>
    where
        T: CsiDriverProvider,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/v1alpha1.CSIDriverProvider/Version" => {
                    #[allow(non_camel_case_types)]
                    struct VersionSvc<T: CsiDriverProvider>(pub Arc<T>);
                    impl<T: CsiDriverProvider>
                        tonic::server::UnaryService<super::VersionRequest> for VersionSvc<T>
                    {
                        type Response = super::VersionResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::VersionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CsiDriverProvider>::version(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = VersionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/v1alpha1.CSIDriverProvider/Mount" => {
                    #[allow(non_camel_case_types)]
                    struct MountSvc<T: CsiDriverProvider>(pub Arc<T>);
                    impl<T: CsiDriverProvider>
                        tonic::server::UnaryService<super::MountRequest> for MountSvc<T>
                    {
                        type Response = super::MountResponse;
                        type Future = BoxFuture<tonic::Response<Self::Response>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MountRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CsiDriverProvider>::mount(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = MountSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => Box::pin(async move {
                    Ok(http::Response::builder()
                        .status(200)
                        .header("grpc-status", tonic::Code::Unimplemented as i32)
                        .header(
                            http::header::CONTENT_TYPE,
                            tonic::metadata::GRPC_CONTENT_TYPE,
                        )
                        .body(empty_body())
                        .unwrap())
                }),
            }
        }
    }
    impl<T: CsiDriverProvider> Clone for CsiDriverProviderServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: CsiDriverProvider> tonic::server::NamedService for CsiDriverProviderServer<T> {
        const NAME: &'static str = "v1alpha1.CSIDriverProvider";
    }
}
