#!/bin/bash

set -e

#
# Setup Oracle TDE for HSM
#
run_sql() {
  SQL="$1"
  SQL2="$2"
  SQL3="$3"
  echo "Running SQL: $SQL"
  cat <<EOF >config.sql
WHENEVER SQLERROR EXIT SQL.SQLCODE;
WHENEVER OSERROR EXIT FAILURE;
$SQL
$SQL2
$SQL3
exit
EOF
  cat config.sql
  docker cp config.sql oracle:/tmp/config.sql
  docker exec -u oracle -i oracle bash -c "sqlplus / as sysdba @/tmp/config.sql"
  rm config.sql
  sleep 3
}

display_wallet() {
  # run_sql "show parameter WALLET_ROOT;" "show parameter TDE_CONFIGURATION;"
  run_sql "COLUMN WRL_PARAMETER FORMAT A50;" "SET LINES 200;" "SELECT WRL_TYPE, WRL_PARAMETER, WALLET_TYPE, STATUS FROM V\$ENCRYPTION_WALLET;"
  run_sql "column name format a40;" "SET LINES 400;" "SELECT KEY_ID,KEYSTORE_TYPE,CREATOR_DBNAME,ACTIVATION_TIME,KEY_USE,ORIGIN FROM V\$ENCRYPTION_KEYS;"
}

run_sql "ALTER SYSTEM SET WALLET_ROOT='/opt/oracle/extapi/64/hsm/Cosmian/libcosmian_pkcs11.so' SCOPE=SPFILE;" "SHUTDOWN IMMEDIATE;" "STARTUP;"
run_sql "ALTER SYSTEM SET TDE_CONFIGURATION='KEYSTORE_CONFIGURATION=HSM' SCOPE=BOTH SID='*';" "SHUTDOWN IMMEDIATE;" "STARTUP;"
run_sql "ADMINISTER KEY MANAGEMENT SET KEYSTORE OPEN IDENTIFIED BY hsm_identity_pass;"
run_sql "ADMINISTER KEY MANAGEMENT SET KEY IDENTIFIED BY hsm_identity_pass;"
# run_sql "ADMINISTER KEY MANAGEMENT CREATE KEY FORCE KEYSTORE IDENTIFIED BY hsm_identity_pass;"

# run_sql "ALTER SYSTEM SET ENCRYPTION KEY IDENTIFIED BY hsm_identity_pass;"

display_wallet

#
# Following commands have been kept. Could be useful for the software wallet migration.
#

# run_sql "CREATE TABLE test_tde (something CHAR(32) ENCRYPT);"

# run_sql "ALTER SYSTEM SET WALLET_ROOT='/etc/ORACLE/KEYSTORES/FREE' SCOPE=SPFILE;" "SHUTDOWN IMMEDIATE;" "STARTUP;"
# run_sql "ALTER SYSTEM SET TDE_CONFIGURATION='KEYSTORE_CONFIGURATION=FILE' SCOPE=BOTH SID='*';" "SHUTDOWN IMMEDIATE;" "STARTUP;"
# run_sql "ADMINISTER KEY MANAGEMENT CREATE KEYSTORE IDENTIFIED BY sw_keystore_pass;"
# run_sql "ADMINISTER KEY MANAGEMENT SET KEYSTORE OPEN IDENTIFIED BY sw_keystore_pass;"

## run_sql "ADMINISTER KEY MANAGEMENT CREATE AUTO_LOGIN KEYSTORE FROM KEYSTORE IDENTIFIED BY sw_keystore_pass;"

## run_sql "ADMINISTER KEY MANAGEMENT SET KEY IDENTIFIED BY sw_keystore_pass WITH BACKUP;"

# run_sql "ADMINISTER KEY MANAGEMENT ADD SECRET 'hsm_identity_pass' FOR CLIENT 'HSM_PASSWORD' IDENTIFIED BY sw_keystore_pass WITH BACKUP;"
## run_sql "ADMINISTER KEY MANAGEMENT ALTER KEYSTORE PASSWORD FORCE KEYSTORE IDENTIFIED BY sw_keystore_pass SET hsm_identity_pass WITH BACKUP;"
# run_sql "ADMINISTER KEY MANAGEMENT CREATE AUTO_LOGIN KEYSTORE FROM KEYSTORE IDENTIFIED BY sw_keystore_pass;"
# run_sql "ADMINISTER KEY MANAGEMENT CREATE AUTO_LOGIN KEYSTORE FROM KEYSTORE '/etc/ORACLE/KEYSTORES/FREE' IDENTIFIED BY sw_keystore_pass;"
# run_sql "ADMINISTER KEY MANAGEMENT CREATE AUTO_LOGIN KEYSTORE FROM KEYSTORE '/etc/ORACLE/KEYSTORES/FREE' IDENTIFIED BY hsm_identity_pass;"

# run_sql "ALTER SYSTEM SET TDE_CONFIGURATION='KEYSTORE_CONFIGURATION=HSM|FILE' SCOPE=BOTH;" "SHUTDOWN IMMEDIATE;" "STARTUP;"
# run_sql "COLUMN WRL_PARAMETER FORMAT A50;" "SET LINES 200;" 'SELECT WRL_TYPE, WRL_PARAMETER, WALLET_TYPE, STATUS FROM V$ENCRYPTION_WALLET;'
# run_sql "ADMINISTER KEY MANAGEMENT SET KEYSTORE OPEN IDENTIFIED BY hsm_identity_pass;"
# run_sql "ADMINISTER KEY MANAGEMENT SET KEYSTORE OPEN IDENTIFIED BY sw_keystore_pass;"
# run_sql "COLUMN WRL_PARAMETER FORMAT A50;" "SET LINES 200;" 'SELECT WRL_TYPE, WRL_PARAMETER, WALLET_TYPE, STATUS FROM V$ENCRYPTION_WALLET;'
# run_sql "ADMINISTER KEY MANAGEMENT SET ENCRYPTION KEY IDENTIFIED BY hsm_identity_pass MIGRATE USING sw_keystore_pass;"
# run_sql "ALTER SYSTEM SET TDE_CONFIGURATION='KEYSTORE_CONFIGURATION=HSM' SCOPE=BOTH SID='*';"

# run_sql "ADMINISTER KEY MANAGEMENT SET KEYSTORE CLOSE IDENTIFIED BY hsm_identity_pass;"
# run_sql "ADMINISTER KEY MANAGEMENT SET KEYSTORE CLOSE IDENTIFIED BY sw_keystore_pass;"
# run_sql "ADMINISTER KEY MANAGEMENT SET KEYSTORE CLOSE CONTAINER = ALL;"
