#!/bin/bash

# export COSMIAN_KMS_CONF="/var/lib/cosmian_vm/data/app/app.conf"

yum update -y && yum install -y redis 

supervisorctl start cosmian_vm_agent

# wait for cert and key to be generated by `cosmian_vm_agent` before starting nginx
until [ -f /var/lib/cosmian_vm/data/cert.pem ]; do sleep 1; done

# reset permissions on cert and key files (SE Linux only)
restorecon -v -R /var/lib/cosmian_vm/data/*

# create directory to write incoming app configuration
mkdir /var/lib/cosmian_vm/data/app

systemctl start nginx