use serde::{Deserialize, Serialize};

use crate::{
    kmip_1_4::{
        kmip_data_structures::CryptographicParameters,
        kmip_types::{
            AlternativeName, ApplicationSpecificInformation, CertificateType,
            CryptographicAlgorithm, CryptographicDomainParameters, CryptographicUsageMask, Digest,
            DigitalSignatureAlgorithm, KeyValueLocationType, Link, Name, ObjectType,
            RandomNumberGenerator, RevocationReason, State, UsageLimits, X509CertificateIdentifier,
        },
    },
    kmip_2_1,
    kmip_2_1::kmip_types::VendorAttribute,
};

/// Attributes structure containing all KMIP 1.4 attributes (51 total)
/// as specified in Chapter 3, paragraphs 3.1 to 3.51
#[derive(Serialize, Deserialize, Clone, Debug, Eq, PartialEq, Default)]
#[serde(rename_all = "PascalCase")]
pub struct Attributes {
    /// The Unique Identifier is generated by the server to uniquely identify a
    /// Managed Object.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unique_identifier: Option<String>,

    /// The Name attribute is a text string used to identify a Managed Object.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<Vec<Name>>,

    /// The Object Type attribute describes the type of Managed Object.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub object_type: Option<ObjectType>,

    /// The Cryptographic Algorithm attribute specifies the algorithm to be used
    /// with the Cryptographic Object.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cryptographic_algorithm: Option<CryptographicAlgorithm>,

    /// The Cryptographic Length attribute specifies the length in bits of the
    /// Cryptographic Object.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cryptographic_length: Option<i32>,

    /// The Cryptographic Parameters attribute is a structure that contains
    /// various cryptographic parameters to be used with the Cryptographic Object.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cryptographic_parameters: Option<CryptographicParameters>,

    /// The Cryptographic Domain Parameters attribute is a structure that contains
    /// various cryptographic domain parameters to be used with the Cryptographic Object.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cryptographic_domain_parameters: Option<CryptographicDomainParameters>,

    /// The Certificate Type attribute is a type of certificate (e.g., X.509).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub certificate_type: Option<CertificateType>,

    /// The Certificate Length attribute specifies the length in bits of the certificate.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub certificate_length: Option<i32>,

    /// The X.509 Certificate Identifier attribute specifies the X.509 certificate identifier.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub x_509_certificate_identifier: Option<X509CertificateIdentifier>,

    /// The X.509 Certificate Subject attribute specifies the subject of the X.509 certificate.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub x_509_certificate_subject: Option<String>,

    /// The X.509 Certificate Issuer attribute specifies the issuer of the X.509 certificate.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub x_509_certificate_issuer: Option<String>,

    /// The Certificate Identifier attribute specifies the identifier of the certificate.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub certificate_identifier: Option<String>,

    /// The Certificate Subject attribute specifies the subject of the certificate.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub certificate_subject: Option<String>,

    /// The Certificate Issuer attribute specifies the issuer of the certificate.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub certificate_issuer: Option<String>,

    /// The Digital Signature Algorithm attribute specifies the algorithm used
    /// to generate the digital signature.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub digital_signature_algorithm: Option<DigitalSignatureAlgorithm>,

    /// The Digest attribute specifies the digest value computed for the object.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub digest: Option<Digest>,

    /// The Operation Policy Name attribute specifies the operation policy for the object.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub operation_policy_name: Option<String>,

    /// The Cryptographic Usage Mask attribute specifies the cryptographic operations
    /// that may be performed using the key.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cryptographic_usage_mask: Option<CryptographicUsageMask>,

    /// The Lease Time attribute specifies the time period during which the client
    /// expects to maintain its interest in the object.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lease_time: Option<i64>,

    /// The Usage Limits attribute specifies limitations on usage of the object.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage_limits: Option<UsageLimits>,

    /// The State attribute specifies the state of the object.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub state: Option<State>,

    /// The Initial Date attribute specifies when the object was initially created.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub initial_date: Option<i64>,

    /// The Activation Date attribute specifies when the object becomes active.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub activation_date: Option<i64>,

    /// The Process Start Date attribute specifies the start date for a cryptographic process.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub process_start_date: Option<i64>,

    /// The Protect Stop Date attribute specifies the stop date for a cryptographic process.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub protect_stop_date: Option<i64>,

    /// The Deactivation Date attribute specifies when the object becomes inactive.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deactivation_date: Option<i64>,

    /// The Destroy Date attribute specifies when the object was destroyed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub destroy_date: Option<i64>,

    /// The Compromise Occurrence Date attribute specifies when a compromise of
    /// the object was detected.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub compromise_occurrence_date: Option<i64>,

    /// The Compromise Date attribute specifies when a compromise of the object
    /// might have occurred.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub compromise_date: Option<i64>,

    /// The Revocation Reason attribute specifies the reason for revocation of the object.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub revocation_reason: Option<RevocationReason>,

    /// The Archive Date attribute specifies when the object was archived.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub archive_date: Option<i64>,

    /// The Object Group attribute specifies the object group to which the object belongs.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub object_group: Option<String>,

    /// The Fresh attribute specifies whether the object is fresh or not.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fresh: Option<bool>,

    /// The Link attribute specifies links to related objects.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub link: Option<Vec<Link>>,

    /// The Application Specific Information attribute specifies information
    /// specific to the application.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub application_specific_information: Option<ApplicationSpecificInformation>,

    /// The Contact Information attribute specifies contact information for the object.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contact_information: Option<String>,

    ///A Custom Attribute is a client- or server-defined attribute intended for vendor-specific purposes.
    /// It is created by the client and not interpreted by the server,
    /// or is created by the server and MAY be interpreted by the client.
    /// All custom attributes created by the client SHALL adhere to a naming scheme,
    /// where the name of the attribute SHALL have a prefix of 'x-'.
    /// All custom attributes created by the key management server SHALL adhere to a naming scheme
    /// where the name of the attribute SHALL have a prefix of 'y-'.
    /// The server SHALL NOT accept a client-created or modified attribute,
    /// where the name of the attribute has a prefix of ‘y-‘.
    /// The tag type Custom Attribute is not able to identify the particular attribute;
    /// hence such an attribute SHALL only appear in an Attribute Structure with
    /// its name as defined in Section 2.1.1.
    /// Note: Cosmian implementation: we map it to a 2.1 `VendorAttribute`
    #[serde(skip_serializing_if = "Option::is_none")]
    pub custom_attribute: Option<Vec<VendorAttribute>>,

    /// The Last Change Date attribute specifies the date and time of the last change.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_change_date: Option<i64>,

    /// The Alternative Name attribute specifies alternative names for the object.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alternative_name: Option<AlternativeName>,

    /// The Key Value Present attribute indicates whether the key value is present
    /// in the object.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub key_value_present: Option<bool>,

    /// The Key Value Location attribute indicates the location of the key value.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub key_value_location: Option<KeyValueLocationType>,

    /// The Original Creation Date attribute specifies the date and time of the
    /// original creation of the object.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub original_creation_date: Option<i64>,

    /// The Random Number Generator attribute specifies the random number generator
    /// used to create the object.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub random_number_generator: Option<RandomNumberGenerator>,

    /// The PKCS#12 Friendly Name attribute specifies the friendly name of the object.
    #[serde(skip_serializing_if = "Option::is_none", rename = "PKCS12FriendlyName")]
    pub pkcs12_friendly_name: Option<String>,

    /// The Description attribute specifies a description of the object.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    /// The Comment attribute specifies a comment for the object.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// The Sensitive attribute indicates whether the object is sensitive.
    #[serde(default)]
    pub sensitive: bool,

    /// The Always Sensitive attribute indicates whether the object has always
    /// been sensitive.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub always_sensitive: Option<bool>,

    /// The Extractable attribute indicates whether the object is extractable.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extractable: Option<bool>,

    /// The Never Extractable attribute indicates whether the object has ever
    /// been extractable.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub never_extractable: Option<bool>,
}

impl From<Attributes> for kmip_2_1::kmip_attributes::Attributes {
    fn from(val: Attributes) -> Self {
        Self {
            unique_identifier: val.unique_identifier.map(|unique_identifier| {
                kmip_2_1::kmip_types::UniqueIdentifier::TextString(unique_identifier)
            }),
            name: val.name.map(|n| n.into_iter().map(Into::into).collect()),
            never_extractable: val.never_extractable,
            object_type: val.object_type.map(Into::into),
            cryptographic_algorithm: val.cryptographic_algorithm.map(Into::into),
            cryptographic_length: val.cryptographic_length.map(Into::into),
            cryptographic_parameters: val.cryptographic_parameters.map(Into::into),
            cryptographic_domain_parameters: val.cryptographic_domain_parameters.map(Into::into),
            certificate_type: val.certificate_type.map(Into::into),
            certificate_length: val.certificate_length.map(Into::into),
            x_509_certificate_identifier: val.x_509_certificate_identifier.map(Into::into),
            x_509_certificate_subject: val.x_509_certificate_subject.map(Into::into),
            x_509_certificate_issuer: val.x_509_certificate_issuer.map(Into::into),
            digital_signature_algorithm: val.digital_signature_algorithm.map(Into::into),
            cryptographic_usage_mask: val.cryptographic_usage_mask.map(Into::into),
            lease_time: val.lease_time.map(Into::into),
            usage_limits: val.usage_limits.map(Into::into),
            state: val.state.map(Into::into),
            initial_date: val.initial_date.map(Into::into),
            activation_date: val.activation_date.map(Into::into),
            process_start_date: val.process_start_date.map(Into::into),
            protect_stop_date: val.protect_stop_date.map(Into::into),
            protection_level: None,
            protection_period: None,
            protection_storage_masks: None,
            deactivation_date: val.deactivation_date.map(Into::into),
            destroy_date: val.destroy_date.map(Into::into),
            compromise_occurrence_date: val.compromise_occurrence_date.map(Into::into),
            compromise_date: val.compromise_date.map(Into::into),
            revocation_reason: val.revocation_reason.map(Into::into),
            rotate_date: None,
            rotate_generation: None,
            rotate_interval: None,
            rotate_latest: None,
            rotate_name: None,
            archive_date: val.archive_date.map(Into::into),
            attribute_index: None,
            object_group: val.object_group.map(Into::into),
            fresh: val.fresh.map(Into::into),
            link: val.link.map(|n| n.into_iter().map(Into::into).collect()),
            application_specific_information: val.application_specific_information.map(Into::into),
            contact_information: val.contact_information.map(Into::into),
            last_change_date: val.last_change_date.map(Into::into),
            alternative_name: val.alternative_name.map(Into::into),
            key_value_present: val.key_value_present.map(Into::into),
            key_value_location: val.key_value_location.map(Into::into),
            original_creation_date: val.original_creation_date.map(Into::into),
            random_number_generator: val.random_number_generator.map(Into::into),
            description: val.description.map(Into::into),
            comment: val.comment.map(Into::into),
            sensitive: val.sensitive,
            always_sensitive: val.always_sensitive.map(Into::into),
            certificate_attributes: None,
            critical: None,
            extractable: None,
            key_format_type: None,
            nist_key_type: None,
            object_group_member: None,
            opaque_data_type: None,
            pkcs_12_friendly_name: None,
            quantum_safe: None,
            rotate_offset: None,
            short_unique_identifier: None,
            vendor_attributes: val
                .custom_attribute
                .map(|n| n.into_iter().map(Into::into).collect()),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Attribute {
    UniqueIdentifier(String),
    Name(Vec<Name>),
    ObjectType(ObjectType),
    CryptographicAlgorithm(CryptographicAlgorithm),
    CryptographicLength(i32),
    CryptographicParameters(CryptographicParameters),
    CryptographicDomainParameters(CryptographicDomainParameters),
    CertificateType(CertificateType),
    CertificateLength(i32),
    X509CertificateIdentifier(X509CertificateIdentifier),
    X509CertificateSubject(String),
    X509CertificateIssuer(String),
    CertificateIdentifier(String),
    CertificateSubject(String),
    CertificateIssuer(String),
    DigitalSignatureAlgorithm(DigitalSignatureAlgorithm),
    Digest(Digest),
    OperationPolicyName(String),
    CryptographicUsageMask(CryptographicUsageMask),
    LeaseTime(i64),
    UsageLimits(UsageLimits),
    State(State),
    InitialDate(i64),
    ActivationDate(i64),
    ProcessStartDate(i64),
    ProtectStopDate(i64),
    DeactivationDate(i64),
    DestroyDate(i64),
    CompromiseOccurrenceDate(i64),
    CompromiseDate(i64),
    RevocationReason(RevocationReason),
    ArchiveDate(i64),
    ObjectGroup(String),
    Fresh(bool),
    Link(Vec<Link>),
    ApplicationSpecificInformation(ApplicationSpecificInformation),
    ContactInformation(String),
    LastChangeDate(i64),
    CustomAttribute(VendorAttribute),
    AlternativeName(AlternativeName),
    KeyValuePresent(bool),
    KeyValueLocation(KeyValueLocationType),
    OriginalCreationDate(i64),
    RandomNumberGenerator(RandomNumberGenerator),
    Pkcs12FriendlyName(String),
    Description(String),
    Comment(String),
    Sensitive(bool),
    AlwaysSensitive(bool),
    Extractable(bool),
    NeverExtractable(bool),
}
