kms_public_url = "https://localhost:9998"

[tls]
tls_p12_file = "/home/hatem/Desktop/repos/kms/test_data/certificates/client_server/server/kmserver.acme.com.p12"
tls_p12_password = "password"
clients_ca_cert_file = "/home/hatem/Desktop/repos/kms/test_data/certificates/client_server/ca/ca.crt"

[ui_config]
ui_index_html_folder = "/home/hatem/Desktop/repos/kms/ui/dist"

[idp_auth]
jwt_auth_provider = ["https://demo-kms.eu.auth0.com/,https://demo-kms.eu.auth0.com/.well-known/jwks.json,rGRvFjjLDBro8gRwxghKuiu207wKfKyG"]

[ui_config.ui_oidc_auth]
ui_oidc_client_id = "rGRvFjjLDBro8gRwxghKuiu207wKfKyG"
ui_oidc_issuer_url = "https://demo-kms.eu.auth0.com/"
ui_oidc_logout_url = "https://demo-kms.eu.auth0.com/logout"
