use std::{
    collections::HashMap,
    sync::mpsc::{self, Sender},
    thread,
};

use actix_web::{
    App, HttpResponse, HttpServer,
    dev::ServerHandle,
    get,
    web::{self, Data},
};
use http::{
    HeaderMap, HeaderValue, StatusCode,
    header::{ACCEPT, CONTENT_TYPE},
};
use oauth2::{
    AuthUrl, ClientId, ClientSecret, CsrfToken, PkceCodeChallenge, PkceCodeVerifier, RedirectUrl,
    Scope, TokenUrl, basic::BasicClient,
};
use serde::{Deserialize, Serialize};
use url::Url;

use super::{HttpClientError, error::result::HttpClientResult};

#[derive(Serialize, Deserialize, Eq, PartialEq, Debug, Clone)]
pub struct Oauth2LoginConfig {
    /// The client ID of your application.
    pub client_id: String,
    /// The client secret of your application.
    pub client_secret: String,
    /// The authorization URL of the provider.
    /// For example, for Google it is `https://accounts.google.com/o/oauth2/v2/auth`.
    pub authorize_url: String,
    /// The token URL of the provider.
    /// For example, for Google it is `https://oauth2.googleapis.com/token`.
    pub token_url: String,
    /// The scopes to request.
    /// For example, for Google it is `["openid", "email"]`.
    pub scopes: Vec<String>,
}

/// This struct holds the state of the login process.
/// It is used to generate the authorization URL and to store the PKCE verifier
/// and the CSRF token.
///
/// The user should browse to the authorization URL and follow the instructions
/// to authenticate. The Url can be recovered by accessing to field `auth_url`.
///
/// The CSRF token is used to verify that the authorization code received on the
/// redirect URL matches the one generated by the client.
/// The PKCE verifier is used to verify that the authorization code received on
/// the redirect URL matches the one generated by the client.
/// See [RFC 7636](https://tools.ietf.org/html/rfc7636) for more details.
/// See [PKCE](https://oauth.net/2/pkce/) for more details.
/// See [CSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery) for more details.
/// See [OAuth2](https://oauth.net/2/) for more details.
/// See [OAuth2 RFC](https://tools.ietf.org/html/rfc6749) for more details.
pub struct LoginState {
    login_config: Oauth2LoginConfig,
    redirect_url: Url,
    pub auth_url: Url,
    pkce_verifier: PkceCodeVerifier,
    csrf_token: CsrfToken,
}

/// This function initializes the login process.
/// It returns a `LoginState` that holds the state of the login process.
///
/// The process should be completed by instructing the user to browse to the
/// authorization URL and follow the instructions to authenticate
/// and immediately after calling `finalize()` with the returned `LoginState`.
///
/// The Url can be recovered by accessing `auth_url` on the returned
/// `LoginState` struct.
impl TryFrom<Oauth2LoginConfig> for LoginState {
    type Error = HttpClientError;

    fn try_from(login_config: Oauth2LoginConfig) -> Result<Self, Self::Error> {
        // if the port is specified in the environment variable, use it
        let port = if let Ok(port_s) = std::env::var("OAUTH2_REDIRECT_URL_PORT") {
            port_s.parse::<u16>().map_err(|e| {
                HttpClientError::Default(format!("Invalid OAUTH2_REDIRECT_URL_PORT: {e:?}"))
            })?
        } else {
            17_899_u16
        };
        Self::build(login_config, port)
    }
}

impl LoginState {
    /// Build a `LoginState` using the given explicit redirect port.
    ///
    /// This is the internal constructor shared by `TryFrom` and the
    /// test-only `try_from_with_port` helper.
    fn build(login_config: Oauth2LoginConfig, port: u16) -> HttpClientResult<Self> {
        let mut redirect_url = Url::parse("http://localhost:17899/authorization")?;
        redirect_url.set_port(Some(port)).map_err(|()| {
            HttpClientError::Default(format!("Failed to set redirect URL port to {port}"))
        })?;

        // Create an OAuth2 client by specifying the client ID, client secret,
        // authorization URL and token URL.
        let client = BasicClient::new(ClientId::new(login_config.client_id.clone()))
            .set_client_secret(ClientSecret::new(login_config.client_secret.clone()))
            .set_auth_uri(AuthUrl::new(login_config.authorize_url.clone())?)
            .set_token_uri(TokenUrl::new(login_config.token_url.clone())?)
            // Set the URL the user will be redirected to after the authorization process.
            .set_redirect_uri(RedirectUrl::new(redirect_url.to_string())?);

        // Generate a PKCE challenge.
        let (pkce_challenge, pkce_verifier) = PkceCodeChallenge::new_random_sha256();

        let scopes = login_config
            .scopes
            .iter()
            .map(|s| Scope::new(s.clone()))
            .collect::<Vec<_>>();

        // Generate the full authorization URL.
        let auth_request = client
            .authorize_url(CsrfToken::new_random)
            // Set the desired scopes.
            .add_scopes(scopes)
            // Set the PKCE code challenge.
            .set_pkce_challenge(pkce_challenge);
        let (auth_url, csrf_token) = auth_request.url();

        // This is the URL you should redirect the user to,
        // in order to trigger the authorization process.
        Ok(Self {
            login_config,
            redirect_url,
            auth_url,
            pkce_verifier,
            csrf_token,
        })
    }

    /// Construct a `LoginState` bound to an explicit `port`, bypassing the
    /// `OAUTH2_REDIRECT_URL_PORT` environment variable.
    ///
    /// Only available in test builds.  Lets each test bind its own port so
    /// parallel tests never collide on the same socket.
    #[cfg(test)]
    pub(crate) fn try_from_with_port(
        login_config: Oauth2LoginConfig,
        port: u16,
    ) -> HttpClientResult<Self> {
        Self::build(login_config, port)
    }

    /// This function finalizes the login process.
    /// It returns the access token.
    ///
    /// This function should be called immediately after the user has been
    /// instructed to browse to the authorization URL. It starts a server on
    /// localhost:17899 and waits for the authorization code to be received
    /// from the browser window. Once the code is received, the server is closed
    /// and the code is returned.
    ///
    /// # Errors
    ///
    /// This function can return a `HttpClientError` in the following cases:
    ///
    /// * The authorization code, state, or other parameters are not received
    ///   from the redirect URL.
    /// * The received state does not match the CSRF token.
    /// * The authorization code is not received on authentication.
    /// * The code received on authentication does not match the CSRF token.
    /// * The access token cannot be requested from the Identity Provider.
    /// * The token exchange request fails.
    /// * The token exchange response cannot be parsed.
    pub async fn finalize(&self) -> HttpClientResult<String> {
        // recover the authorization code, state and other parameters from the redirect
        // URL.  Use the port that was actually embedded in the redirect URL at
        // construction time (respects OAUTH2_REDIRECT_URL_PORT).
        let port = self.redirect_url.port_or_known_default().unwrap_or(17_899);
        let (auth_parameters, server_handle) = Self::receive_authorization_parameters(port)?;
        // Gracefully stop the redirect listener so the port is freed immediately
        // rather than lingering in TIME_WAIT.  This prevents port-binding
        // failures when the test suite is run multiple times in quick succession.
        server_handle.stop(true).await;

        // Once the user has been redirected to the redirect URL, you'll have access to
        // the authorization code. For security reasons, your code should verify
        // that the `state` parameter returned by the server matches
        // `csrf_state`.
        let received_state = auth_parameters.get("state").ok_or_else(|| {
            HttpClientError::Default("state not received on authentication".to_owned())
        })?;
        if received_state != self.csrf_token.secret() {
            return Err(HttpClientError::Default(
                "state received on authentication does not match".to_owned(),
            ));
        }

        // extract the authorization code
        let authorization_code = auth_parameters.get("code").ok_or_else(|| {
            HttpClientError::Default("code not received on authentication".to_owned())
        })?;

        let token_result = request_token(
            &self.login_config,
            &self.redirect_url,
            &self.pkce_verifier,
            authorization_code,
        )
        .await?;

        Ok(match token_result.id_token {
            // this is where Google returns the JWT token
            Some(id_token) => id_token,
            None => token_result.access_token,
        })
    }

    /// This function starts the server on the given `port` and waits for the
    /// authorization code to be received from the browser window. Once the
    /// code is received, the server handle is returned alongside the parameters
    /// so the caller can gracefully stop the server and free the port.
    ///
    /// The port must match the one embedded in the redirect URL that was sent
    /// to the Identity Provider during the authorization request.
    #[allow(clippy::unwrap_used)]
    fn receive_authorization_parameters(
        port: u16,
    ) -> HttpClientResult<(HashMap<String, String>, ServerHandle)> {
        let (auth_params_tx, auth_params_rx) = mpsc::channel::<HashMap<String, String>>();
        let (server_handle_tx, server_handle_rx) = mpsc::sync_channel::<ServerHandle>(1);
        // Spawn the server into a runtime
        let tokio_handle = tokio::runtime::Handle::current();
        let _task = thread::spawn(move || {
            tokio_handle.block_on(async move {
                // server.await
                #[get("/authorization")]
                async fn authorization_handler(
                    auth_params: web::Query<HashMap<String, String>>,
                    auth_params_tx: Data<Sender<HashMap<String, String>>>,
                ) -> HttpResponse {
                    auth_params_tx
                        .into_inner()
                        .send(auth_params.into_inner())
                        .unwrap();
                    HttpResponse::Ok().body("You can now close this window.")
                }

                let server = HttpServer::new(move || {
                    App::new()
                        .app_data(Data::new(auth_params_tx.clone()))
                        .service(authorization_handler)
                })
                .bind(("127.0.0.1", port))?
                .run();
                // Send the handle before awaiting so the outer thread can stop
                // the server once the first callback has been received.
                drop(server_handle_tx.send(server.handle()));
                server.await
            })
        });
        let params = auth_params_rx.recv().map_err(|e| {
            HttpClientError::Default(format!("authorization code not received: {e:?}"))
        })?;
        let handle = server_handle_rx
            .recv_timeout(std::time::Duration::from_secs(5))
            .map_err(|e| HttpClientError::Default(format!("server handle not received: {e:?}")))?;
        Ok((params, handle))
    }
}

#[derive(Deserialize, Debug)]
#[allow(dead_code)]
pub(crate) struct OAuthResponse {
    pub access_token: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id_token: Option<String>,
    #[serde(skip)]
    pub expires_in: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub refresh_token: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub token_type: Option<String>,
}

/// This function requests the access token from the Identity Provider.
///
/// This function was rewritten because Google returns the JWT token in the
/// `id_token` field, not in the `access_token` field.
///
/// For Google see: <https://developers.google.com/identity/openid-connect/openid-connect#obtainuserinfo>
///
/// # Arguments
///
/// * `login_config` - The `Oauth2LoginConfig` containing the client
///   configuration.
/// * `redirect_url` - The redirect URL used in the `OAuth2` flow.
/// * `pkce_verifier` - The PKCE code verifier used in the `OAuth2` flow.
/// * `authorization_code` - The authorization code received from the Identity
///   Provider.
///
/// # Errors
///
/// This function can return a `HttpClientError` in the following cases:
///
/// * The token exchange request fails.
/// * The token exchange response cannot be parsed.
pub(crate) async fn request_token(
    login_config: &Oauth2LoginConfig,
    redirect_url: &Url,
    pkce_verifier: &PkceCodeVerifier,
    authorization_code: &str,
) -> HttpClientResult<OAuthResponse> {
    let params = vec![
        ("grant_type", "authorization_code"),
        ("redirect_uri", redirect_url.as_str()),
        ("client_id", login_config.client_id.as_str()),
        ("code", authorization_code),
        ("client_secret", login_config.client_secret.as_str()),
        ("code_verifier", pkce_verifier.secret()),
    ];

    let mut headers = HeaderMap::new();
    headers.append(ACCEPT, HeaderValue::from_static("application/json"));
    headers.append(
        CONTENT_TYPE,
        HeaderValue::from_static("application/x-www-form-urlencoded"),
    );

    let body = url::form_urlencoded::Serializer::new(String::new())
        .extend_pairs(params)
        .finish();

    let client = super::HttpClient::instantiate(&super::HttpClientConfig {
        server_url: login_config.token_url.clone(),
        accept_invalid_certs: true,
        ..Default::default()
    })
    .map_err(|e| HttpClientError::Default(format!("failed to create HTTP client: {e}")))?;

    let mut extra_headers = HeaderMap::new();
    extra_headers.append(ACCEPT, HeaderValue::from_static("application/json"));

    let response = client
        .post_form(&login_config.token_url, &body, &extra_headers)
        .await
        .map_err(|e| {
            HttpClientError::Default(format!("failed issuing token exchange request: {e:?}"))
        })?;

    if response.status != StatusCode::OK {
        let error_text = response
            .text()
            .unwrap_or_else(|_| "<failed to read response>".to_owned());
        return Err(HttpClientError::Default(format!(
            "failed token exchange: {error_text}"
        )));
    }

    response.json().map_err(|e| {
        HttpClientError::Default(format!("failed parsing token exchange response: {e:?}"))
    })
}

/// Configuration for the Cosmian authentication server login.
///
/// Used by the `ckms login cosmian` subcommand.  Set the corresponding
/// `cosmian_conf` section in the KMS client configuration file:
///
/// ```toml
/// [http_config.cosmian_conf]
/// server_url = "https://auth.example.com"
/// realm      = "kms"
/// ```
#[derive(Serialize, Deserialize, Eq, PartialEq, Debug, Clone)]
pub struct CosmianAuthServerLoginConfig {
    /// Base URL of the Cosmian authentication server (no trailing slash).
    pub server_url: String,
    /// Realm to authenticate against (e.g. `"kms"`).
    pub realm: String,
}

/// The next step the authentication server requires after a login attempt.
///
/// Mirrors the server-side `AuthenticationNextStep` enum, serialized as `PascalCase`
/// string variants (e.g. `"TotpRequired"`).
#[derive(Deserialize, Debug, Clone, PartialEq, Eq)]
pub(super) enum AuthenticationNextStep {
    /// Authentication succeeded; the session cookie is set.
    Authenticated,
    /// Server requires a TOTP code before granting the session.
    TotpRequired,
    /// The user's password has expired and must be changed before logging in.
    ChangePassword,
}

/// JSON body returned by the authentication server on every login response.
#[derive(Deserialize, Debug)]
struct AuthenticationResult {
    next_step: AuthenticationNextStep,
}

/// The outcome of a [`cosmian_login`] call.
#[derive(Debug)]
pub enum CosmianLoginStep {
    /// Authentication succeeded. Contains the JWT extracted from the `_ea_` cookie.
    Authenticated(String),
    /// The server requires a TOTP code. Re-call [`cosmian_login`] with `totp_code: Some(...)`.
    TotpRequired,
}

/// Login to a Cosmian authentication server using HTTP Basic credentials.
///
/// Sends `POST {server_url}/login?realm={realm}` with an
/// `Authorization: Basic <base64(username:password)>` header.
///
/// If `totp_code` is `Some`, it is included in the JSON body so that TOTP
/// verification is completed in a single request. Pass `None` on the first
/// call; if the server responds with [`CosmianLoginStep::TotpRequired`],
/// prompt the user and re-call with the code.
///
/// On success the JWT is extracted from the `Set-Cookie: _ea_=<JWT>` header
/// and returned inside [`CosmianLoginStep::Authenticated`]. The caller stores
/// it in `http_config.access_token` and forwards it as a Bearer token on every
/// subsequent KMS request.
///
/// # Errors
///
/// Returns [`HttpClientError`] if the HTTP request fails, the server responds
/// with a non-2xx status, the password has expired, or the `_ea_` cookie is
/// absent from a successful response.
pub async fn cosmian_login(
    config: &CosmianAuthServerLoginConfig,
    username: &str,
    password: &str,
    // TODO: remove accept_invalid_certs
    accept_invalid_certs: bool,
    totp_code: Option<&str>,
) -> HttpClientResult<CosmianLoginStep> {
    /// Name of the session cookie set by the Cosmian authentication server.
    const COSMIAN_SESSION_COOKIE: &str = "_ea_";

    let mut url = Url::parse(config.server_url.trim_end_matches('/'))
        .map_err(|e| HttpClientError::Default(format!("Invalid Cosmian auth server URL: {e:?}")))?;
    url.path_segments_mut()
        .map_err(|()| {
            HttpClientError::Default("Invalid Cosmian auth server URL: cannot be a base".to_owned())
        })?
        .push("login");
    url.query_pairs_mut().append_pair("realm", &config.realm);

    let body = totp_code.map_or_else(
        || "{}".to_owned(),
        |code| format!(r#"{{"totp_code":"{code}"}}"#),
    );

    let client = reqwest::Client::builder()
        // TODO: remove accept_invalid_certs
        .danger_accept_invalid_certs(accept_invalid_certs)
        .build()
        .map_err(|e| HttpClientError::Default(format!("Failed to build reqwest client: {e:?}")))?;
    let response = client
        .post(url)
        .basic_auth(username, Some(password))
        .header(reqwest::header::CONTENT_TYPE, "application/json")
        .body(body)
        .send()
        .await
        .map_err(|e| HttpClientError::Default(format!("Cosmian login request failed: {e:?}")))?;

    let status = response.status();
    if !status.is_success() {
        let error_text = response
            .text()
            .await
            .unwrap_or_else(|_| "<failed to read response>".to_owned());
        return Err(HttpClientError::Default(format!(
            "Cosmian login failed ({status}): {error_text}"
        )));
    }

    // Collect headers before consuming the response body.
    let headers = response.headers().clone();

    // Parse the JSON body to determine the authentication next step.
    let body_bytes = response.bytes().await.map_err(|e| {
        HttpClientError::Default(format!("Failed to read login response body: {e}"))
    })?;
    let result: AuthenticationResult = serde_json::from_slice(&body_bytes)
        .map_err(|e| HttpClientError::Default(format!("Failed to parse login response: {e}")))?;

    match result.next_step {
        AuthenticationNextStep::TotpRequired => return Ok(CosmianLoginStep::TotpRequired),
        AuthenticationNextStep::ChangePassword => {
            return Err(HttpClientError::Default(
                "Your password has expired. Please change it via the Cosmian authentication \
                 server before logging in."
                    .to_owned(),
            ));
        }
        AuthenticationNextStep::Authenticated => {}
    }

    // The access token is delivered via `Set-Cookie: _ea_=<JWT>; ...`.
    // There may be multiple Set-Cookie headers; find the first one whose
    // cookie name is exactly `_ea_`.
    for header_value in headers.get_all(reqwest::header::SET_COOKIE) {
        let raw = header_value
            .to_str()
            .map_err(|e| HttpClientError::Default(format!("invalid Set-Cookie header: {e}")))?;

        // Each Set-Cookie value has the form:
        //   name=value[; attribute[=value]]*
        // Split at the first ';' to isolate the name=value pair, then split
        // at the first '=' to separate name from value.
        let name_value = raw.split(';').next().unwrap_or(raw);
        if let Some((name, value)) = name_value.split_once('=') {
            if name.trim() == COSMIAN_SESSION_COOKIE {
                return Ok(CosmianLoginStep::Authenticated(value.trim().to_owned()));
            }
        }
    }

    Err(HttpClientError::Default(format!(
        "Cosmian login response did not set the `{COSMIAN_SESSION_COOKIE}` session cookie"
    )))
}
