[book]
title = "Key Management System"
authors = ["Cosmian"]
language = "en"
src = "docs"

[build]
build-dir = "book"
create-missing = false

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
site-url = "https://docs.cosmian.com/"
additional-css = ["theme/css/eviden.css", "theme/css/mdbook-admonish.css", "theme/css/tabs.css"]
additional-js = ["theme/mermaid.min.js", "theme/js/mermaid-init.js", "theme/js/tabs.js", "theme/js/theme-invert.js", "theme/js/old-versions-link.js"]

[output.html.search]
enable = true

[output.html.fold]
enable = true
level = 1

[preprocessor.tabs]
command = "python3 ./theme/scripts/mdbook_tabs.py"

[preprocessor.admonish_compat]
command = "python3 ./theme/scripts/mdbook_admonish_compat.py"
before = ["admonish"]

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.1.0"

[preprocessor.mermaid]
command = "mdbook-mermaid"
