[package]
name = "pkcs11_sys"
version = "0.2.17"
description = "Generated bindings for pkcs11.h. Useful for building PKCS#11 modules in rust."
authors = [
    "Brandon Weeks <bweeks@google.com>",
    "Kevin King <kcking@google.com>",
]
license = "Apache-2.0"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[build-dependencies]
bindgen = { version = "0.69.4", optional = true }
