---
name: Docker main workflow

on:
  workflow_call:

env:
  REGISTRY: ghcr.io

jobs:
  pyo3:
    uses: ./.github/workflows/maturin.yml
    with:
      toolchain: nightly-2024-06-09

  not-fips-image:
    name: Not FIPS image build and tests
    uses: ./.github/workflows/build_docker_image.yml
    with:
      prefix: ''
      features: ''
      registry-image: ghcr.io/cosmian/kms

  fips-image:
    name: FIPS image build and tests
    uses: ./.github/workflows/build_docker_image.yml
    with:
      prefix: FIPS
      features: --features=fips
      registry-image: ghcr.io/cosmian/kms-fips
