---
name: Build all

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string

jobs:
  centos7:
    uses: ./.github/workflows/build_centos7.yml
    secrets: inherit
    with:
      toolchain: ${{ inputs.toolchain }}
      archive-name: centos7
      commands: |
        cargo build --release --bins

        # Check binaries
        target/release/ckms -h
        target/release/cosmian_kms_server -h
      artifacts: |
        target/release/ckms
        target/release/cosmian_kms_server

  rhel9:
    uses: ./.github/workflows/build_rhel9.yml
    secrets: inherit
    with:
      toolchain: ${{ inputs.toolchain }}
      archive-name: rhel9
      commands: |
        cargo build --release --bins

        # Check binaries
        target/release/ckms -h
        target/release/cosmian_kms_server -h
      artifacts: |
        target/release/ckms
        target/release/cosmian_kms_server

  fips-centos7:
    uses: ./.github/workflows/build_centos7.yml
    secrets: inherit
    with:
      toolchain: ${{ inputs.toolchain }}
      archive-name: fips_centos7
      commands: |
        cargo build --release --bins --features fips

        # Check binaries
        target/release/ckms -h
        target/release/cosmian_kms_server -h
      artifacts: |
        /usr/local/openssl
        target/release/ckms
        target/release/cosmian_kms_server

  ubuntu-20:
    uses: ./.github/workflows/build_generic.yml
    secrets: inherit
    with:
      toolchain: ${{ inputs.toolchain }}
      distribution: ubuntu-20.04
      archive-name: ubuntu_20_04
      commands: |
        cargo build --release --bins

        # Check binaries
        target/release/ckms -h
        target/release/cosmian_kms_server -h
      artifacts: |
        target/release/ckms
        target/release/cosmian_kms_server

  fips-ubuntu-20:
    uses: ./.github/workflows/build_generic.yml
    secrets: inherit
    with:
      toolchain: ${{ inputs.toolchain }}
      distribution: ubuntu-20.04
      archive-name: fips_ubuntu_20_04
      commands: |
        cargo build --release --bins --features fips

        # Check binaries
        target/release/ckms -h
        target/release/cosmian_kms_server -h
      artifacts: |
        /usr/local/openssl
        target/release/ckms
        target/release/cosmian_kms_server

  ubuntu-22:
    uses: ./.github/workflows/build_generic.yml
    secrets: inherit
    with:
      toolchain: ${{ inputs.toolchain }}
      distribution: ubuntu-22.04
      archive-name: ubuntu_22_04
      commands: |
        cargo build --release --bins

        # Check binaries
        target/release/ckms -h
        target/release/cosmian_kms_server -h
      artifacts: |
        target/release/ckms
        target/release/cosmian_kms_server

  windows:
    uses: ./.github/workflows/build_generic.yml
    with:
      toolchain: ${{ inputs.toolchain }}
      distribution: ubuntu-20.04
      archive-name: windows
      commands: |
        sudo apt-get install --no-install-recommends -qq libclang-dev gcc-mingw-w64-x86-64
        rustup target add x86_64-pc-windows-gnu

        # build only `ckms`
        cargo build -p cosmian_kms_cli --target x86_64-pc-windows-gnu --no-default-features

        sudo mkdir -p /usr/local/openssl
        sudo chown -R $USER /usr/local/openssl
        bash ./scripts/local_ossl_instl.sh /usr/local/openssl cross-compile-windows

        cargo build --bins --target x86_64-pc-windows-gnu
      artifacts: |
        target/x86_64-pc-windows-gnu/release/ckms.exe
        target/x86_64-pc-windows-gnu/release/cosmian_kms_server.exe

  mac:
    uses: ./.github/workflows/build_generic.yml
    with:
      toolchain: ${{ inputs.toolchain }}
      distribution: macos-12
      archive-name: macos
      commands: |
        rustup target add x86_64-apple-darwin
        cargo build --release --bins --target x86_64-apple-darwin

        # Check binaries
        target/x86_64-apple-darwin/release/ckms -h
        target/x86_64-apple-darwin/release/cosmian_kms_server -h
      artifacts: |
        target/x86_64-apple-darwin/release/ckms
        target/x86_64-apple-darwin/release/cosmian_kms_server

  cosmian_vm:
    needs:
      - ubuntu-22
      - rhel9
    uses: ./.github/workflows/build_and_test_cosmian_vm.yml
    strategy:
      matrix:
        distrib: [ubuntu, rhel]
    name: ${{ matrix.distrib }} -> GCP KMS Cosmian VM image
    secrets: inherit
    with:
      distrib: ${{ matrix.distrib }}
