---
name: Build all

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string

jobs:
  centos7:
    uses: ./.github/workflows/build_centos7.yml
    secrets: inherit
    with:
      toolchain: ${{ inputs.toolchain }}
      archive-name: centos7
      target: x86_64-unknown-linux-gnu
      debug_or_release: release

  fips-centos7:
    uses: ./.github/workflows/build_centos7.yml
    secrets: inherit
    with:
      toolchain: ${{ inputs.toolchain }}
      archive-name: fips_centos7
      target: x86_64-unknown-linux-gnu
      debug_or_release: release
      features: fips
      artifacts: |
        /usr/local/openssl

  rhel9:
    uses: ./.github/workflows/build_rhel9.yml
    secrets: inherit
    with:
      toolchain: ${{ inputs.toolchain }}
      archive-name: rhel9
      target: x86_64-unknown-linux-gnu
      debug_or_release: release

  fips-ubuntu-20:
    uses: ./.github/workflows/build_generic.yml
    secrets: inherit
    with:
      toolchain: ${{ inputs.toolchain }}
      distribution: ubuntu-20.04
      archive-name: fips_ubuntu_20_04
      target: x86_64-unknown-linux-gnu
      debug_or_release: release
      features: fips
      skip_services_tests: --skip test_mysql --skip test_pgsql --skip test_redis --skip google_cse
      artifacts: |
        /usr/local/openssl

  ubuntu-22:
    uses: ./.github/workflows/build_generic.yml
    secrets: inherit
    with:
      toolchain: ${{ inputs.toolchain }}
      distribution: ubuntu-22.04
      archive-name: ubuntu_22_04
      target: x86_64-unknown-linux-gnu
      debug_or_release: release
      skip_services_tests: --skip test_mysql --skip test_pgsql --skip test_redis --skip google_cse

  ubuntu-24:
    uses: ./.github/workflows/build_generic.yml
    secrets: inherit
    with:
      toolchain: ${{ inputs.toolchain }}
      distribution: ubuntu-24.04
      archive-name: ubuntu_24_04
      target: x86_64-unknown-linux-gnu
      debug_or_release: release
      skip_services_tests: --skip test_mysql --skip test_pgsql --skip test_redis --skip google_cse

  windows:
    uses: ./.github/workflows/build_windows.yml
    with:
      toolchain: ${{ inputs.toolchain }}
      archive-name: windows
      commands: |
        rustup target add x86_64-pc-windows-msvc

        # build only `ckms`
        cd crate/cli
        cargo build --release --target x86_64-pc-windows-msvc

        # build pkcs11 provider
        cd ../pkcs11/provider
        cargo build --release --target x86_64-pc-windows-msvc
        cd ../../..

        $env:VCPKG_INSTALLATION_ROOT
        dir $env:VCPKG_INSTALLATION_ROOT
        vcpkg install openssl[fips]

        vcpkg integrate install
        set VCPKGRS_DYNAMIC=1
        $env:OPENSSL_DIR="$env:VCPKG_INSTALLATION_ROOT\packages\openssl_x64-windows"

        cd crate/server
        cargo build --release --target x86_64-pc-windows-msvc
      artifacts: |
        target/x86_64-pc-windows-msvc/release/ckms.exe
        target/x86_64-pc-windows-msvc/release/cosmian_kms_server.exe
        target/x86_64-pc-windows-msvc/release/ckms_pkcs11.dll

  mac:
    uses: ./.github/workflows/build_generic.yml
    with:
      toolchain: ${{ inputs.toolchain }}
      distribution: macos-12
      archive-name: macos
      target: x86_64-apple-darwin
      debug_or_release: release
      skip_services_tests: --skip test_mysql --skip test_pgsql --skip test_redis --skip google_cse

  # MACOS ARM BUILD
  macos14:
    uses: ./.github/workflows/build_generic.yml
    with:
      toolchain: ${{ inputs.toolchain }}
      distribution: macos-14
      archive-name: macos14
      target: aarch64-apple-darwin
      debug_or_release: release
      skip_services_tests: --skip test_mysql --skip test_pgsql --skip test_redis --skip google_cse
