---
name: Cargo lint

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-lint-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-lint-${{ hashFiles('**/Cargo.lock') }}

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.toolchain }}
          components: rustfmt, clippy

      # Ensure all code has been formatted with rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check --color always

      - name: Static analysis
        run: cargo clippy --workspace --all-targets --all-features --release -- -D warnings
