---
name: CI
run-name: CI (${{ github.head_ref || github.ref_name }})

on:
  push:
    branches:
      - develop
      - main
    tags:
      - "**"
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: 0 0 * * * # Daily at midnight

jobs:
  main:
    secrets: inherit
    uses: ./.github/workflows/main_base.yml
    with:
      toolchain: 1.90.0
