---
name: KMS Python build

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string

jobs:
  pyo3-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - run: |
          rustup default ${{ inputs.toolchain }}
          rustup target add x86_64-unknown-linux-gnu

      - uses: actions/setup-python@v4
        with:
          python-version: 3
          cache: pip # caching pip dependencies

      - name: Prerequisites
        run: |
          set -x
          pip install maturin==1.2.3
          sudo apt-get install --no-install-recommends -qq libclang-dev pkg-config

          # build openssl
          pushd .
          cd /tmp
          wget https://openssl.org/source/old/1.1.1/openssl-1.1.1v.tar.gz
          tar -xf openssl-1.1.1v.tar.gz
          cd openssl-1.1.1v
          ./config --prefix=/usr/local/ssl --openssldir=/usr/local/ssl
          make -j
          sudo make install_sw
          cd ..
          rm -rf openssl-1.1.1v*
          popd

          cd crate/pyo3/python
          pip install -r requirements.txt

      - name: Python maturin build
        run: |
          pushd crate/pyo3
          OPENSSL_DIR=/usr/local/ssl maturin build --release --target x86_64-unknown-linux-gnu --target-dir target_python
          popd

      - run: find target/

      - name: Upload WHL for Linux
        uses: actions/upload-artifact@v3
        with:
          name: kms_python_linux
          path: target/wheels/*manylinux*.whl
          retention-days: 1
          if-no-files-found: error

      - name: Upload WHL for cloudproof_python tests
        uses: actions/upload-artifact@v3
        with:
          name: python-x86_64-unknown-linux-gnu
          path: target/wheels/*manylinux*.whl
          retention-days: 1
          if-no-files-found: error

  pyo3-windows:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          rustup default ${{ inputs.toolchain }}
          rustup target add x86_64-pc-windows-gnu

      - uses: actions/setup-python@v4
        with:
          python-version: 3
          cache: pip # caching pip dependencies

      - name: Prerequisites
        run: |
          set -x
          pip install maturin==1.2.3
          sudo apt-get install --no-install-recommends -qq libclang-dev gcc-mingw-w64-x86-64 pkg-config

          # build openssl
          pushd .
          cd /tmp
          wget https://openssl.org/source/old/1.1.1/openssl-1.1.1v.tar.gz
          tar -xf openssl-1.1.1v.tar.gz
          cd openssl-1.1.1v
          ./Configure --cross-compile-prefix=x86_64-w64-mingw32- mingw64 --prefix=/usr/local/ssl --openssldir=/usr/local/ssl
          make -j
          sudo make install_sw
          cd ..
          rm -rf openssl-1.1.1v*
          popd

          cd crate/pyo3/python
          pip install -r requirements.txt

      - name: Python maturin build
        run: |
          pushd crate/pyo3
          OPENSSL_DIR=/usr/local/ssl maturin build --release --target x86_64-pc-windows-gnu --target-dir target_python
          popd

      - name: Upload WHL for Windows
        uses: actions/upload-artifact@v3
        with:
          name: kms_python_windows
          path: target/wheels/*win*.whl
          retention-days: 1
          if-no-files-found: error

  pyo3-mac:
    strategy:
      fail-fast: false
      matrix:
        include:
          - mac-version: macos-12
            archive-name: kms_python_macos_intel
            target: x86_64-apple-darwin

          - mac-version: macos-14
            archive-name: kms_python_macos_arm
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.mac-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.13
          cache: pip # caching pip dependencies

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-06-09
          components: rustfmt, clippy

      - name: Prerequisites for macos
        run: |
          set -x

          pip3 install maturin==1.2.3

      - name: Python maturin build
        run: |
          set -x
          cd crate/pyo3
          maturin build --release --target ${{ matrix.target }} --target-dir target_python

      - name: Upload WHL for MacOS
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.archive-name }}
          path: target/wheels/*macosx*.whl
          retention-days: 1
          if-no-files-found: error
