---
name: Packaging

on:
  push:
    tags:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_call:
jobs:
  # Run packaging for PRs
  packaging:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    uses: ./.github/workflows/packaging.yml
    secrets: inherit
    with:
      toolchain: 1.90.0
