---
name: PyKMIP Tests

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string

jobs:
  pykmip-tests:
    runs-on: ubuntu-24.04
    container: python:3.11

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install base deps (bash, curl) and build deps
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            bash \
            curl \
            libssl-dev \
            build-essential \
            pkg-config

      - name: Install rustup silently
        shell: bash
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.toolchain }}
          components: rustfmt, clippy

      - name: Tests PyKMIP
        shell: bash
        env:
          COSMIAN_KMS_CONF: ./scripts/kms.toml
        run: |
          cargo run --bin cosmian_kms --features non-fips &

          python3 -m pip install --upgrade pip
          python3 -m venv .venv
          source .venv/bin/activate
          pip install PyKMIP
          bash ./scripts/test_pykmip.sh all
