---
name: Docker

on:
  workflow_call:

env:
  REGISTRY: ghcr.io
  REGISTRY_IMAGE: ghcr.io/cosmian/kms

jobs:
  pyo3:
    uses: ./.github/workflows/python_build.yml
    with:
      toolchain: nightly-2023-03-20

  build-and-push-image:
    runs-on: ubuntu-latest
    container: docker:19.03.15

    steps:
      - uses: actions/checkout@v1

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Display docker metadata
        run: |
          echo steps.meta.outputs.version: ${{ steps.meta.outputs.version }}
          echo steps.meta.outputs.tags: ${{ steps.meta.outputs.tags }}
          echo env.REGISTRY_IMAGE:github.ref_name: ${{ env.REGISTRY_IMAGE }}:${{ github.ref_name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push docker container
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY_IMAGE }}:${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
          file: delivery/Dockerfile.standalone

      - name: Re-tag docker for git tags
        if: startsWith(github.ref, 'refs/tags')
        env:
          BUILD_IMAGE: ${{ env.REGISTRY_IMAGE }}:${{ github.ref_name }}
        run: |
          # Get the latest main image
          docker pull ${{ env.REGISTRY_IMAGE }}:main
          # Tag it with the tag name
          docker tag ${{ env.REGISTRY_IMAGE }}:main ${BUILD_IMAGE}
          # Push the tagged image
          docker push ${BUILD_IMAGE}

      - name: Docker check container
        run: |
          docker run --rm ${{ steps.meta.outputs.tags }} --help

    outputs:
      image-tag: ${{ steps.meta.outputs.version }}

  python_tests:
    needs:
      - build-and-push-image
      - pyo3
    uses: ./.github/workflows/python_tests.yml
    secrets: inherit
    with:
      kms-version: ${{ needs.build-and-push-image.outputs.image-tag }}
