---
name: Docker

on:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cosmian/kms

jobs:
  pyo3:
    uses: ./.github/workflows/python_build.yml
    with:
      toolchain: nightly-2023-03-20

  build-and-push-image:
    runs-on: ubuntu-latest
    container: docker:19.03.15

    steps:
      - uses: actions/checkout@v1

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker build for development
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: delivery/Dockerfile.standalone

      - name: Display docker tag
        run: echo ${{ steps.meta.outputs.version }}

    outputs:
      image-tag: ${{ steps.meta.outputs.version }}

  python_tests:
    needs:
      - build-and-push-image
      - pyo3
    uses: ./.github/workflows/python_tests.yml
    secrets: inherit
    with:
      kms-version: ${{ needs.build-and-push-image.outputs.image-tag }}
